# Site
repository: brh1984/resume_template
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brandon Horsley
title: Senior Project Manager
email: brandon082084@gmail.com
phone: 713-923-0036 
# website: https://brh1984.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: brandonrhorsley
facebook_username: brandon.horsley.56
# github_username:  brh1984
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brandon Horsley, and I'm a senior project manager at Siemens Gamesa Renewable Energy. I have experience in engineering, process improvement, and training. I've worked in project management in the energy sector for 11 years, gaining teamwork and leadership skills.  In addition to my professional career, I've been happily married for 6 years and have two wonderful kids with a third on the way!

  I am most skilled in: <mark>Project Managment</mark>, <mark>Process Improvement</mark>, and <mark>Project Collaboration</mark>

content:
  - title: Fun Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Profile Web Page
        link: github.com/brh1984/brh1984.github.io
        # link_text: Project Website
        additional_links:
          - title:  My Profile Web Page Project
            icon: fab fa-github
            url: github.com/brh1984/brh1984.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Siemens Gamesa Renewable Energy
        link: https://www.siemensgamesa.com/en-int
        link_text: siemensgamesa.com
        sub_title: Senior Project Manager, Americas Region
        caption: 2017 - Present
        quote: > 
            As Senior Project Manager I am responsible for multiple large projects in our portfolio at a time.  I have a strong focus on collaboration with stakholders from multiple departments in multiple regions, to ensure project success and best practice sharing.
        description: | # this will include new lines to allow paragraphs
            <br>           
            <ul>
            <li><font size="-0.5">Manage 30-40% of project portfolio, worth ~$10 Million in positive P&L impact per year throughout North and South America.</font></li>
            <li><font size="-0.5">Develop strong collaborative relationships with stakeholders across other departments and other countries to achieve project targets and overall business objectives.</font></li>
            <li><font size="-0.5">Responsible for evaluating project improvement ideas, business case development, and managing the execution of project plans across global & regional functions.</font></li>
            <li><font size="-0.5">Managed the development, testing, and implementation of web portal and software to streamline service history recording and tracking across fleet of 3000+ turbines in North America.</font></li>
            <li><font size="-0.5">Develop and manage detailed scheduling, financial planning, risk mitigation, and stakeholder communication for large regional projects.</font></li>
            <li><font size="-0.5">Responsible for preparing and presenting project review updates to business executives and global leadership teams.</font></li>
            <li><font size="-0.5">Reduced preventive maintenance downtime by 36% in North America, and warehouse processing time by 50% in Latin America.</font></li>
            </ul>

      - layout: top-middle
        title: Siemens Energy, Inc
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Senior Project Manager, Americas Region
        caption: 2013 - 2017
        quote: | #At Siemens Gamesa, we're constantly working on better solutions for renewables – to provide cleaner, more reliable and more affordable energy to society, and to create lasting value for all stakeholders.
            <p style="font-style: italic;">As a project manager I was responsible for seeing all my projects through from defining to closing, as well as coach other project managers through the same process.</p>
        description: | # this will include new lines to allow paragraphs
            <br>           
            <ul>
            <li><font size="-0.5">Managed projects from define to closing stages, building project teams, reporting to stakeholders, and managing project schedules and financials, leading to $2.77 million in positive P&L impact.</font></li>
            <li><font size="-0.5">Assumed management of struggling projects, recovering $2.05 million in previous losses.</font></li>
            <li><font size="-0.5">	Coached leads on projects worth $2.75 Million in positive P&L impact across multiple departments.</font></li>
            </ul>

      - layout: top-middle
        title: Siemens Energy, Inc
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Process Engineer
        caption: 2012 - 2013
        quote: | #At Siemens Gamesa, we're constantly working on better solutions for renewables – to provide cleaner, more reliable and more affordable energy to society, and to create lasting value for all stakeholders.
            <p style="font-style: italic;">This role focused on delivering specific measurable improvements for processes in supply chain, engineering, sales, and operations.</p>
        description: | # this will include new lines to allow paragraphs
            <br>           
            <ul>
            <li><font size="-0.5">Organized and led process improvement events across North American service sites, totaling $313K in annual labor savings, reducing service lead times by 20%.</font></li>
            <li><font size="-0.5">Developed and ran training for 39 field personnel to run process improvements at their own sites, increasing project capacity from 1 event a week to 5-8 events a week, and increasing sustainability of event outcomes.</font></li>
            <li><font size="-0.5">Identified and remediated at least 24 safety concerns while in the field</font></li>
            </ul>
            
      - layout: top-middle
        title: Siemens Energy, Inc
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Engineer in Training Program
        caption: 2011 - 2012
        quote: | #At Siemens Gamesa, we're constantly working on better solutions for renewables – to provide cleaner, more reliable and more affordable energy to society, and to create lasting value for all stakeholders.
            <p style="font-style: italic;">The Engineer in Training program gave me a stong introduction to the wind energy business and a broad overview of different departments and their roles in the company.  I'm greatful for the network and knowledge I gained that became the foundation for my career with the company</p>
        description: | # this will include new lines to allow paragraphs
            <br>           
            <ul>
            <li><font size="-0.5">Worked as Service Technician for 8 weeks, completing advanced rescue training for wind turbines, and advanced troubleshooting training.</font></li>
            <li><font size="-0.5">Assisted in site manager duties including customer reporting, leading morning safety meetings, financial reporting, and ground crew support.</font></li>
            <li><font size="-0.5">Managed small continuous improvement projects consisting of training teams, facilitating workshops, and executing workshop outcomes.</font></li>
            <li><font size="-0.5">Developed program for organizing and running community service projects in towns around field sites.</font></li>
            </ul>
           
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
