# Site
repository: brh1984/resume_template
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brandon Horsley
title: Senior Project Manager
email: brandon082084@gmail.com
phone: 713-923-0036 
# website: https://brh1984.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: brandonrhorsley
facebook_username: brandon.horsley.56
# github_username:  brh1984
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brandon Horsley, and I'm a senior project manager at Siemens Gamesa Renewable Energy. I have experience in engineering, process improvement, and training. I've worked in project management in the energy sector for 11 years, gaining teamwork and leadership skills.  In addition to my professional career, I've been happily married for 6 years and have two wonderful kids with a third on the way!

  I am most skilled in: <mark>Project Managment</mark>, <mark>Process Improvement</mark>, and <mark>Project Collaboration</mark>

content:
  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Profile Web Page
        link: github.com/brh1984/brh1984.github.io
        # link_text: Project Website
        additional_links:
          - title:  My Profile Web Page Project
            icon: fab fa-github
            url: github.com/brh1984/brh1984.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “Tell me and I forget, teach me and I may remember, involve me and I learn.”
          ― Benjamin Franklin
        description: | # this will include new lines to allow paragraphs
          For me, the best way to learn is by doing.  This project gave me a chance to learn some newer ways to create a web page and a brush up on things I've learned in the past.  A fun way to share my work experience and a little more about me.  Hope you like it!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Senior Project Manager, Americas Region
        link: https://www.siemensgamesa.com/en-int
        link_text: siemensgamesa.com
        sub_title: Siemens Gamesa Renewable Energy
        caption: 2017 - Present
        quote: > 
            As Senior Project Manager I am responsible for multiple large projects in our portfolio at a time.  I have a strong focus on collaboration with stakholders from multiple departments in multiple regions, to ensure project success and best practice sharing.
        description: | # this will include new lines to allow paragraphs      
            <ul>
            <li><font size="-0.5">Manage 30-40% of project portfolio, worth ~$10 Million in positive P&L impact per year throughout North and South America.</font></li>
            <li><font size="-0.5">Develop strong collaborative relationships with stakeholders across other departments and other countries to achieve project targets and overall business objectives.</font></li>
            <li><font size="-0.5">Responsible for evaluating project improvement ideas, business case development, and managing the execution of project plans across global & regional functions.</font></li>
            <li><font size="-0.5">Managed the development, testing, and implementation of web portal and software to streamline service history recording and tracking across fleet of 3000+ turbines in North America.</font></li>
            <li><font size="-0.5">Develop and manage detailed scheduling, financial planning, risk mitigation, and stakeholder communication for large regional projects.</font></li>
            <li><font size="-0.5">Responsible for preparing and presenting project review updates to business executives and global leadership teams.</font></li>
            <li><font size="-0.5">Reduced preventive maintenance downtime by 36% in North America, and warehouse processing time by 50% in Latin America.</font></li>
            </ul>

      - layout: top-middle
        title: Project Manager, Americas Region
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Siemens Energy, Inc
        caption: 2013 - 2017
        quote: >
            As a project manager I was responsible for seeing all my projects through from defining to closing, as well as coach other project managers through the same process.
        description: | # this will include new lines to allow paragraphs
            <ul>
            <li><font size="-0.5">Managed projects from define to closing stages, building project teams, reporting to stakeholders, and managing project schedules and financials, leading to $2.77 million in positive P&L impact.</font></li>
            <li><font size="-0.5">Assumed management of struggling projects, recovering $2.05 million in previous losses.</font></li>
            <li><font size="-0.5">	Coached leads on projects worth $2.75 Million in positive P&L impact across multiple departments.</font></li>
            </ul>

      - layout: top-middle
        title: Process Engineer
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Siemens Energy, Inc
        caption: 2012 - 2013
        quote: >
            This role focused on delivering specific measurable improvements for processes in supply chain, engineering, sales, and operations.
        description: | # this will include new lines to allow paragraphs
            <ul>
            <li><font size="-0.5">Organized and led process improvement events across North American service sites, totaling $313K in annual labor savings, reducing service lead times by 20%.</font></li>
            <li><font size="-0.5">Developed and ran training for 39 field personnel to run process improvements at their own sites, increasing project capacity from 1 event a week to 5-8 events a week, and increasing sustainability of event outcomes.</font></li>
            <li><font size="-0.5">Identified and remediated at least 24 safety concerns while in the field</font></li>
            </ul>
            
      - layout: top-middle
        title: Engineer in Training Program
        link: https://www.siemens-energy.com/us/en.html?gclid=Cj0KCQjwidSWBhDdARIsAIoTVb23wRe8QoKQWdkBxCfg6Q_FEQHNQmGvBPMk4KXSgtOXEQXv1Pc9wsQaAj1EEALw_wcB
        link_text: siemens-energy.com
        sub_title: Siemens Energy, Inc
        caption: 2011 - 2012
        quote: >
            The Engineer in Training program gave me a stong introduction to the wind energy business and a broad overview of different departments and their roles in the company.  I'm greatful for the network and knowledge I gained that became the foundation for my career with the company.
        description: | # this will include new lines to allow paragraphs
            <ul>
            <li><font size="-0.5">Worked as Service Technician for 8 weeks, completing advanced rescue training for wind turbines, and advanced troubleshooting training.</font></li>
            <li><font size="-0.5">Assisted in site manager duties including customer reporting, leading morning safety meetings, financial reporting, and ground crew support.</font></li>
            <li><font size="-0.5">Managed small continuous improvement projects consisting of training teams, facilitating workshops, and executing workshop outcomes.</font></li>
            <li><font size="-0.5">Developed program for organizing and running community service projects in towns around field sites.</font></li>
            </ul>
           
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Brigham Young University
        caption: 2010 - 2013
        sub_title: BSc Mechanical Engineering
        quote: >
          A BYU education should be spiritually strengthening, intellectually enlarging, and character building, leading to lifelong learning and service. -The Aims of a BYU Education-
        description: | # this will include new lines to allow paragraphs
          During my time at BYU I focused not only on my major in engineering, but in taking other classes that would make me well rounded.  Public speaking, Personal Finance, and World History classes were a few.  I joined one of my professors over a summer to assist in graduate research on the propogation of gravity waves in the ocean and atomosphere.  I was a member of Engineers without boarders, traveling to Peru to install a wind turbine in a small village.  I was able to do an internship with Atlas Copco in Nanjing, China.  Finally, I graduated magna cum laude in 2011 when I was recruited by Siemens Energy. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
